name: .NET Build CI

on:
  push:
    branches: [ fix_security_issues ]
  pull_request:
    branches: [ fix_security_issues ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Install .NET Framework 4.8 Developer Pack
      run: |
        choco install netfx-4.8-devpack -y
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
